version: "3"

services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/app/
     # - node_modules:/app/node_modules
    ports:
      - 3000:3000

  prod:
    build:
      context: .
    # volumes:
     # - node_modules:/app/node_modules
    ports:
      - 3000:3000

# volumes:
#   node_modules: