version: "3.7"
services:
  webapp:
    build: 
      context: .
      target: dev
    command: npm run start:dev
    ports:
      - '8082:3000'
    volumes:
      - .:/app
      - api_node_modules:/app/node_modules
volumes:
  api_node_modules: